<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient Details - {{ $patient->patient_name ?? 'Unknown Patient' }}</title>
    <!-- Tailwind CSS CDN -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <!-- Chart.js CDN -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>
</head>
<body class="bg-gray-100">
<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <!-- Temporary Access Notice -->
    <div class="bg-blue-50 border-l-4 border-blue-400 p-4 mb-8">
        <div class="flex">
            <div class="flex-shrink-0">
                <svg class="h-5 w-5 text-blue-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2h-1V9z" clip-rule="evenodd" />
                </svg>
            </div>
            <div class="ml-3">
                <p class="text-sm text-blue-700">
                    You are viewing temporary access to {{ $patient->patient_name ?? 'Unknown Patient' }}'s details.
                    This link was generated by <span class="font-semibold">{{ $generatedByUserName }}</span> and will expire at {{ now()->addHours(24)->format('g:i A, M j, Y') }}.
                </p>
            </div>
        </div>
    </div>

    <!-- Patient Header -->
    <div class="bg-white shadow rounded-lg overflow-hidden mb-8">
        <div class="px-6 py-4">
            <div class="flex items-center">
                <div class="flex-shrink-0 h-12 w-12 rounded-full bg-gradient-to-r from-blue-500 to-indigo-600 flex items-center justify-center text-white font-bold text-xl">
                    {{ strtoupper(substr($patient->patient_name ?? 'U', 0, 1)) }}
                </div>
                <div class="ml-4">
                    <h3 class="text-lg font-medium text-gray-900">{{ $patient->patient_name ?? 'Unknown Patient' }}</h3>
                    <div class="flex items-center text-sm text-gray-500 mt-1">
                        <span>🩸 {{ $patient->blood_type ?? 'Blood type not specified' }}</span>
                        <span class="mx-2">•</span>
                        <span>Medical Record: {{ $patient->medical_record_number ?? 'N/A' }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Patient Details -->
    <div class="bg-white rounded-lg shadow overflow-hidden mb-8">
        <div class="px-6 py-4 border-b border-gray-200">
            <h3 class="text-lg font-medium text-gray-900">Patient Information</h3>
        </div>
        <div class="px-6 py-4 grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
                <span class="text-sm text-gray-600">Height:</span>
                <p class="text-gray-900">{{ $patient->height ? $patient->height . ' cm' : 'N/A' }}</p>
            </div>
            <div>
                <span class="text-sm text-gray-600">Current Weight:</span>
                <p class="text-gray-900">{{ $patient->current_weight ? $patient->current_weight . ' kg' : 'N/A' }}</p>
            </div>
            <div>
                <span class="text-sm text-gray-600">Allergies:</span>
                <p class="text-gray-900">{{ $patient->allergies ?? 'None' }}</p>
            </div>
            <div>
                <span class="text-sm text-gray-600">Chronic Conditions:</span>
                <p class="text-gray-900">{{ $patient->chronic_conditions ?? 'None' }}</p>
            </div>
            <div>
                <span class="text-sm text-gray-600">Current Medications:</span>
                <p class="text-gray-900">{{ $patient->current_medications ?? 'None' }}</p>
            </div>
            <div>
                <span class="text-sm text-gray-600">Insurance Provider:</span>
                <p class="text-gray-900">{{ $patient->insurance_provider ?? 'N/A' }}</p>
            </div>
            <div>
                <span class="text-sm text-gray-600">Insurance Policy Number:</span>
                <p class="text-gray-900">{{ $patient->insurance_policy_number ?? 'N/A' }}</p>
            </div>
            <div>
                <span class="text-sm text-gray-600">Family Medical History:</span>
                <p class="text-gray-900">{{ $patient->family_medical_history ?? 'None' }}</p>
            </div>
            <div>
                <span class="text-sm text-gray-600">Activity Level:</span>
                <p class="text-gray-900">{{ $patient->activity_level ? ucfirst(str_replace('_', ' ', $patient->activity_level)) : 'N/A' }}</p>
            </div>
            <div>
                <span class="text-sm text-gray-600">Smoker:</span>
                <p class="text-gray-900">{{ $patient->smoker ? 'Yes' : 'No' }}</p>
            </div>
            <div>
                <span class="text-sm text-gray-600">Alcohol Consumption:</span>
                <p class="text-gray-900">{{ $patient->alcohol_consumption ? $patient->alcohol_consumption . ' drinks/week' : 'None' }}</p>
            </div>
            <div>
                <span class="text-sm text-gray-600">Dietary Restrictions:</span>
                <p class="text-gray-900">{{ $patient->dietary_restrictions ?? 'None' }}</p>
            </div>
        </div>
    </div>

    <!-- Current Vitals Cards -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
        <div class="bg-white rounded-lg shadow p-6 text-center">
            <div class="w-16 h-16 bg-gradient-to-br from-blue-100 to-blue-200 rounded-full flex items-center justify-center mx-auto mb-4">
                <svg class="h-8 w-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
                </svg>
            </div>
            <div class="text-3xl font-bold text-gray-900 mb-2">
                {{ $latestVitals ? ($latestVitals->systolic_bp . '/' . $latestVitals->diastolic_bp) : '--/--' }}
            </div>
            <div class="text-sm text-gray-600 font-medium">Blood Pressure</div>
            <div class="text-xs text-gray-400 mt-1">mmHg</div>
            <div class="text-xs text-gray-500 mt-2">
                {{ $latestVitals ? $latestVitals->measured_at->format('M j, g:i A') : '--' }}
            </div>
        </div>

        <div class="bg-white rounded-lg shadow p-6 text-center">
            <div class="w-16 h-16 bg-gradient-to-br from-blue-100 to-blue-200 rounded-full flex items-center justify-center mx-auto mb-4">
                <svg class="h-8 w-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
                </svg>
            </div>
            <div class="text-3xl font-bold text-gray-900 mb-2">
                {{ $latestVitals ? $latestVitals->heart_rate : '--' }}
            </div>
            <div class="text-sm text-gray-600 font-medium">Heart Rate</div>
            <div class="text-xs text-gray-400 mt-1">bpm</div>
            <div class="text-xs text-gray-500 mt-2">
                {{ $latestVitals ? $latestVitals->measured_at->format('M j, g:i A') : '--' }}
            </div>
        </div>
    </div>

    <!-- Vital Signs Trends Chart -->
    <div class="bg-white rounded-lg shadow overflow-hidden mb-8">
        <div class="px-6 py-4 border-b border-gray-200">
            <h3 class="text-lg font-medium text-gray-900">Vital Signs Trends</h3>
        </div>
        <div class="p-6">
            <div class="relative h-96">
                <canvas id="vitalsChart"></canvas>
            </div>
        </div>
    </div>

    <!-- Recent Vitals History -->
    <div class="bg-white rounded-lg shadow overflow-hidden">
        <div class="px-6 py-4 border-b border-gray-200">
            <h3 class="text-lg font-medium text-gray-900">Recent Vitals History</h3>
        </div>
        <div class="divide-y divide-gray-200">
            @forelse($recentVitals as $vital)
                <div class="px-6 py-4 hover:bg-gray-50 cursor-pointer" data-vital='@json($vital)'>
                    <div class="flex items-center justify-between">
                        <div>
                            <p class="text-sm font-medium text-gray-900">
                                {{ $vital->measured_at->format('M j, g:i A') }}
                            </p>
                            <div class="flex items-center mt-1 text-sm text-gray-500">
                                <span class="mr-4">BP: {{ $vital->systolic_bp ?? '--' }}/{{ $vital->diastolic_bp ?? '--' }}</span>
                                <span class="mr-4">HR: {{ $vital->heart_rate ?? '--' }} bpm</span>
                                <span class="mr-4">Temp: {{ $vital->temperature ? $vital->temperature . ' ' . $vital->temperature_unit : '--' }}</span>
                                <span>O2: {{ $vital->oxygen_saturation ? $vital->oxygen_saturation . '%' : '--' }}</span>
                            </div>
                        </div>
                        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium
                            {{ $vital->status === 'critical' ? 'bg-red-100 text-red-800' :
                               ($vital->status === 'warning' ? 'bg-yellow-100 text-yellow-800' : 'bg-green-100 text-green-800') }}">
                            {{ ucfirst($vital->status ?? 'normal') }}
                        </span>
                    </div>
                </div>
            @empty
                <div class="px-6 py-12 text-center">
                    <p class="text-gray-500">No recent vital signs recorded</p>
                </div>
            @endforelse
        </div>
    </div>

    <!-- Vital Signs Details Modal -->
    <div id="vitalDetailsModal" class="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full hidden">
        <div class="relative top-20 mx-auto p-5 border w-11/12 md:w-2/3 lg:w-1/2 shadow-lg rounded-md bg-white">
            <div class="mt-3">
                <div class="flex justify-between items-center mb-4">
                    <h3 class="text-lg leading-6 font-medium text-gray-900">Vital Signs Details</h3>
                    <button onclick="closeVitalDetailsModal()" class="text-gray-400 hover:text-gray-500">
                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6" id="vitalDetailsContent">
                    <!-- Content will be populated by JavaScript -->
                </div>
            </div>
        </div>
    </div>


<!-- Medications -->
<div class="bg-white rounded-lg shadow overflow-hidden mb-8">
    <div class="px-6 py-4 border-b border-gray-200">
        <h3 class="text-lg font-medium text-gray-900">Current Medications</h3>
    </div>
    <div class="divide-y divide-gray-200">
        @forelse($medications as $med)
            <div class="px-6 py-4 hover:bg-gray-50">
                <div class="flex items-center justify-between">
                    <div>
                        <p class="text-sm font-medium text-gray-900">
                            {{ $med->name }} ({{ $med->generic_name ?? 'N/A' }})
                        </p>
                        <div class="flex items-center mt-1 text-sm text-gray-500">
                            <span class="mr-4">Dosage: {{ $med->dosage }}</span>
                            <span class="mr-4">Frequency: {{ $med->frequency }}</span>
                            <span>Start Date: {{ $med->start_date->format('M j, Y') }}</span>
                        </div>
                        @if($med->instructions)
                            <p class="text-sm text-gray-600 mt-1">{{ $med->instructions }}</p>
                        @endif
                    </div>
                    <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium
                        {{ $med->status === 'active' ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800' }}">
                        {{ ucfirst($med->status) }}
                    </span>
                </div>
            </div>
        @empty
            <div class="px-6 py-12 text-center">
                <p class="text-gray-500">No medications recorded</p>
            </div>
        @endforelse
    </div>
</div>

<!-- Doctor-Prescribed Medications -->
<div class="bg-white rounded-lg shadow overflow-hidden mb-8">
    <div class="px-6 py-4 border-b border-gray-200">
        <h3 class="text-lg font-medium text-gray-900">Doctor-Prescribed Medications</h3>
    </div>
    <div class="divide-y divide-gray-200">
        @forelse($doctorMedications as $med)
            <div class="px-6 py-4 hover:bg-gray-50">
                <div class="flex items-center justify-between">
                    <div>
                        <p class="text-sm font-medium text-gray-900">
                            {{ $med->name }} ({{ $med->generic_name ?? 'N/A' }})
                        </p>
                        <div class="flex items-center mt-1 text-sm text-gray-500">
                            <span class="mr-4">Dosage: {{ $med->dosage }}</span>
                            <span class="mr-4">Frequency: {{ $med->frequency }}</span>
                            <span class="mr-4">Start Date: {{ $med->start_date->format('M j, Y') }}</span>
                            <span>Prescribed By: {{ $med->doctor_name ?? $med->prescribed_by ?? 'N/A' }}</span>
                        </div>
                        @if($med->purpose)
                            <p class="text-sm text-gray-600 mt-1">Purpose: {{ $med->purpose }}</p>
                        @endif
                        @if($med->instructions)
                            <p class="text-sm text-gray-600 mt-1">Instructions: {{ $med->instructions }}</p>
                        @endif
                        @if($med->health_tips)
                            <p class="text-sm text-gray-600 mt-1">Health Tips: {{ $med->health_tips }}</p>
                        @endif
                        <p class="text-sm text-gray-600 mt-1">Refills: {{ $med->refills }}</p>
                    </div>
                    <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium
                        {{ $med->status === 'active' ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800' }}">
                        {{ ucfirst($med->status) }}
                    </span>
                </div>
            </div>
        @empty
            <div class="px-6 py-12 text-center">
                <p class="text-gray-500">No doctor-prescribed medications recorded</p>
            </div>
        @endforelse
    </div>
</div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    // Initialize the vitals chart
    const ctx = document.getElementById('vitalsChart').getContext('2d');
    const vitalsChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: @json($chartData['labels'] ?? []),
            datasets: [
                {
                    label: 'Systolic BP',
                    data: @json($chartData['systolic'] ?? []),
                    borderColor: '#ef4444',
                    backgroundColor: 'rgba(239, 68, 68, 0.1)',
                    tension: 0.4,
                    fill: true
                },
                {
                    label: 'Diastolic BP',
                    data: @json($chartData['diastolic'] ?? []),
                    borderColor: '#f97316',
                    backgroundColor: 'rgba(249, 115, 22, 0.1)',
                    tension: 0.4,
                    fill: false
                },
                {
                    label: 'Heart Rate',
                    data: @json($chartData['heart_rate'] ?? []),
                    borderColor: '#3b82f6',
                    backgroundColor: 'rgba(59, 130, 246, 0.1)',
                    tension: 0.4,
                    fill: false,
                    hidden: true
                },
                {
                    label: 'Temperature',
                    data: @json($chartData['temperature'] ?? []),
                    borderColor: '#f59e0b',
                    backgroundColor: 'rgba(245, 158, 11, 0.1)',
                    tension: 0.4,
                    fill: false,
                    hidden: true
                },
                {
                    label: 'Oxygen Saturation',
                    data: @json($chartData['oxygen'] ?? []),
                    borderColor: '#10b981',
                    backgroundColor: 'rgba(16, 185, 129, 0.1)',
                    tension: 0.4,
                    fill: false,
                    hidden: true
                }
            ]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: {
                    position: 'top',
                },
                tooltip: {
                    mode: 'index',
                    intersect: false,
                }
            },
            scales: {
                y: {
                    beginAtZero: false
                }
            }
        }
    });

    // Function to show vital details modal
    window.showVitalDetails = function(vitalData) {
        const modalContent = document.getElementById('vitalDetailsContent');

        // Format the data for display
        modalContent.innerHTML = `
            <div class="space-y-4">
                <div class="bg-blue-50 p-4 rounded-lg">
                    <h4 class="font-semibold text-blue-800 mb-2">Basic Information</h4>
                    <div class="grid grid-cols-2 gap-2">
                        <div>
                            <span class="text-sm text-gray-600">Date & Time:</span>
                            <p class="font-medium">${new Date(vitalData.measured_at).toLocaleString()}</p>
                        </div>
                        <div>
                            <span class="text-sm text-gray-600">Status:</span>
                            <p class="font-medium">
                                <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium
                                    ${vitalData.status === 'critical' ? 'bg-red-100 text-red-800' :
                                       (vitalData.status === 'warning' ? 'bg-yellow-100 text-yellow-800' : 'bg-green-100 text-green-800')}">
                                    ${vitalData.status ? vitalData.status.charAt(0).toUpperCase() + vitalData.status.slice(1) : 'Normal'}
                                </span>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="bg-white p-4 rounded-lg border border-gray-200">
                    <h4 class="font-semibold text-gray-800 mb-2">Vital Measurements</h4>
                    <div class="grid grid-cols-2 gap-4">
                        <div class="bg-gray-50 p-3 rounded-lg">
                            <span class="text-sm text-gray-600">Blood Pressure:</span>
                            <p class="text-xl font-bold">${vitalData.systolic_bp || '--'}/${vitalData.diastolic_bp || '--'} mmHg</p>
                        </div>
                        <div class="bg-gray-50 p-3 rounded-lg">
                            <span class="text-sm text-gray-600">Heart Rate:</span>
                            <p class="text-xl font-bold">${vitalData.heart_rate || '--'} bpm</p>
                        </div>
                        <div class="bg-gray-50 p-3 rounded-lg">
                            <span class="text-sm text-gray-600">Temperature:</span>
                            <p class="text-xl font-bold">${vitalData.temperature ? vitalData.temperature + ' ' + vitalData.temperature_unit : '--'}</p>
                        </div>
                        <div class="bg-gray-50 p-3 rounded-lg">
                            <span class="text-sm text-gray-600">Oxygen Saturation:</span>
                            <p class="text-xl font-bold">${vitalData.oxygen_saturation ? vitalData.oxygen_saturation + '%' : '--'}</p>
                        </div>
                        ${vitalData.weight ? `
                        <div class="bg-gray-50 p-3 rounded-lg">
                            <span class="text-sm text-gray-600">Weight:</span>
                            <p class="text-xl font-bold">${vitalData.weight} ${vitalData.weight_unit}</p>
                        </div>
                        ` : ''}
                        ${vitalData.blood_glucose ? `
                        <div class="bg-gray-50 p-3 rounded-lg">
                            <span class="text-sm text-gray-600">Blood Glucose:</span>
                            <p class="text-xl font-bold">${vitalData.blood_glucose} mg/dL</p>
                        </div>
                        ` : ''}
                    </div>
                </div>
            </div>

            <div class="space-y-4">
                ${vitalData.notes ? `
                <div class="bg-white p-4 rounded-lg border border-gray-200">
                    <h4 class="font-semibold text-gray-800 mb-2">Notes</h4>
                    <p class="text-sm text-gray-700">${vitalData.notes}</p>
                </div>
                ` : ''}
                ${vitalData.symptoms ? `
                <div class="bg-white p-4 rounded-lg border border-gray-200">
                    <h4 class="font-semibold text-gray-800 mb-2">Symptoms</h4>
                    <p class="text-sm text-gray-700">${vitalData.symptoms}</p>
                </div>
                ` : ''}
            </div>
        `;

        document.getElementById('vitalDetailsModal').classList.remove('hidden');
    };

    // Function to close the modal
    window.closeVitalDetailsModal = function() {
        document.getElementById('vitalDetailsModal').classList.add('hidden');
    };

    // Add click handlers to recent vitals rows
    document.querySelectorAll('[data-vital]').forEach(row => {
        row.addEventListener('click', function() {
            const vitalData = JSON.parse(this.getAttribute('data-vital'));
            showVitalDetails(vitalData);
        });
    });
});
</script>
</body>
</html>
